### ISSUE TITLE
1.20.1 error

### ISSUE THREAD

**Issue by comonier** [LeahPy/ImmersiveThunder#8]
testing file: ImmersiveThunder-1.20.1+1.2.2

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Cloth Config v11' (cloth-config) 11.0.99 with version 11.1.106 or later.
Unmet dependency listing:
	 - Mod 'Immersive Thunder' (leahs-immersive-thunder) 1.20.1+1.2.2 requires version 11.1.106 or later of mod 'Cloth Config v11' (cloth-config), but only the wrong version is present: 11.0.99!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by comonier** [comment]
oh ok i should to download that another mod to mods folder, did it new error

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Cloth Config v11' (cloth-config) 11.0.99 with version 11.1.106 or later.
Unmet dependency listing:
	 - Mod 'Immersive Thunder' (leahs-immersive-thunder) 1.20.1+1.2.2 requires version 11.1.106 or later of mod 'Cloth Config v11' (cloth-config), but only the wrong version is present: 11.0.99!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

with a cloth-config-11.1.118-forge file

**Comment by comonier** [comment]
oh a see i use FABRIC not FORGE i shoult to download FABRIC version of the cloth-config

done.

**Comment by comonier** [comment]
ISSUE FIXED

![image](https://github.com/netcatgirl/ImmersiveThunder/assets/19571541/59895557-9151-428a-bfca-9fcff3878d73)

**Comment by comonier** [comment]
TY

**Comment by netcatgirl** [comment]
glad you got it working! :D
